"""Installation file for ansys-mechanical-stubs."""

from datetime import datetime
import os
import sys

from setuptools import find_namespace_packages, setup
from setuptools.command.develop import develop
from setuptools.command.install import install

SCRIPT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "src", "stub_generator")

sys.path.append(os.path.dirname(SCRIPT_DIR))

from stub_generator.create_files import main


class PostDevelopCommand(develop):
    """Post-installation for development mode."""

    def run(self):
        develop.run(self)
        main()


class PostInstallCommand(install):
    """Post-installation for installation mode."""

    def run(self):
        install.run(self)
        main()


# Get the long description from the README file
HERE = os.path.abspath(os.path.dirname(__file__))
with open(os.path.join(HERE, "README.rst"), encoding="utf-8") as f:
    long_description = f.read()

description = f"Autogenerated PyMechanical Stubs package, built on {datetime.now().strftime('%H:%M:%S on %d %B %Y')}"

setup(
    name="ansys-mechanical-stubs",
    packages=find_namespace_packages(where="src", include="ansys*"),
    package_dir={"": "src"},
    version="dev0",
    description=description,
    long_description=long_description,
    license="MIT",
    author="ANSYS, Inc.",
    author_email="pyansys.core@ansys.com",
    maintainer="ANSYS, Inc.",
    maintainer_email="pyansys.core@ansys.com",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Information Analysis",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
    url="<https://github.com/ansys/pymechanical-stubs",
    python_requires=">=3.9,<4",
    install_requires=[
        "ansys-pythonnet",
        "build==1.0.3",
        "certifi==2024.2.2",
        "charset_normalizer==3.3.2",
        "colorama==0.4.6",
        "docutils==0.20.1",
        "flit_core==3.9.0",
        "flit==3.9.0",
        "idna==3.6",
        "importlib_metadata==7.0.1",
        "packaging==23.2",
        "pyproject_hooks==1.0.0",
        "requests==2.31.0",
        "tomli_w==1.0.0",
        "tomli==2.0.1",
        "urllib3==2.2.0",
        "zipp==3.17.0",
    ],
    extras_require={
        "doc": [
            "ansys-sphinx-theme==0.13.2",
            "autodoc_pydantic==2.0.1",
            "jupyter_sphinx==0.5.3",
            "nbsphinx==0.9.3",
            "numpydoc==1.6.0",
            "PyYAML==6.0.1",
            "Sphinx==7.2.6",
            "sphinx-autoapi==3.0.0",
            "sphinx-autodoc-typehints==1.25.3",
            "sphinxcontrib-globalsubs==0.1.1",
            "sphinxcontrib-httpdomain==1.8.1",
            "sphinx-copybutton==0.5.2",
            "sphinx_design==0.5.0",
            "sphinx-jinja==2.0.2",
            "sphinx-markdown-builder==0.6.6",
            "sphinxnotes-strike==1.2.1",
        ],
    },
    project_urls={
        "Source": "https://github.com/ansys/pymechanical-stubs/",
        "Tracker": "https://github.com/ansys/pymechanical-stubs/issues",
        "Homepage": "https://github.com/ansys/pymechanical-stubs",
        "Documentation": "https://scripting.mechanical.docs.pyansys.com",
    },
    include_package_data=True,
    cmdclass={
        "develop": PostDevelopCommand,
        "install": PostInstallCommand,
    },
)
