name: >
  Set up Python

description: |
  Sets up Python on the Mechanical containers using uv.

inputs:

  # Required inputs
  python-version:
    description: >
      Python version to set up. For example, 3.10
    required: true
    type: string

runs:
  using: "composite"
  steps:

    - name: "Install uv and set up Python"
      shell: bash
      run: |
        apt update
        apt install lsb-release git curl make -y
        curl -LsSf https://astral.sh/uv/install.sh | sh
        export PATH="$HOME/.local/bin:$PATH"
        uv python install python${{ inputs.python-version }}
        uv venv --python ${{ inputs.python-version }} /env
        echo "/env/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=/env" >> $GITHUB_ENV
