[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
# Check https://flit.readthedocs.io/en/latest/pyproject_toml.html for all available sections
name = "ansys-mechanical-stubs"
version = "0"
description = "PyMechanical scripting API stubs."
readme = "README.rst"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [
    {name = "ANSYS, Inc.", email = "pyansys.support@ansys.com"},
]
maintainers = [
    {name = "PyAnsys developers", email = "pyansys.maintainers@ansys.com"},
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "ansys-sphinx-theme>=0.8.2",
    "flit>3.8.0",
    "sphinx-notfound-page==0.8.3",
    "numpydoc==1.5.0",
    "build>= 0.10.0",
]

doc = [
    "Sphinx==7.1.2",
    "ansys-sphinx-theme==0.10.4",
    "grpcio==1.57.0",
    "imageio-ffmpeg==0.4.8",
    "imageio==2.31.1",
    "jupyter_sphinx==0.4.0",
    "jupyterlab>=3.2.8",
    "matplotlib==3.7.2",
    "numpydoc==1.5.0",
    "plotly==5.16.1",
    "pypandoc==1.11",
    "pytest-sphinx==0.5.0",
    "pythreejs==2.4.2",
    "pyvista==0.41.1",
    "sphinx-autoapi==2.1.1",
    "sphinx-jinja==2.0.2",
    "sphinx-autobuild==2021.3.14",
    "sphinx-autodoc-typehints==1.24.0",
    "sphinx-copybutton==0.5.1",
    "sphinx_design==0.5.0",
    "sphinx-gallery==0.14.0",
    "sphinx-notfound-page==0.8.3",
    "sphinxcontrib-websupport==1.2.6",
    "sphinxemoji==0.2.0",
]

[tool.flit.module]
name = "Ansys"

[project.urls]
Source = "https://github.com/pyansys/mechanical-stubs/"
Tracker = "https://github.com/pyansys/mechanical-stubs/issues"
Homepage = "https://github.com/pyansys/mechanical-stubs"
