name: GitHub CI
on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main
      - release/*

env:
  PYMECHANICAL_PORT: 10000  # default won't work on GitHub runners
  PYMECHANICAL_START_INSTANCE: FALSE
  DOCKER_PACKAGE: ghcr.io/ansys/mechanical
  DOCKER_IMAGE_VERSION: 23.1.0
  DOCKER_MECH_CONTAINER_NAME: mechanical
  MAIN_PYTHON_VERSION: '3.10'
  PACKAGE_NAME: ansys-mechanical-stubs
  PACKAGE_NAMESPACE: ansys.mechanical.stubs
  DOCUMENTATION_CNAME: scripting.mechanical.docs.pyansys.com

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # style:
  #   name: Code style
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: PyAnsys code style checks
  #       uses: ansys/actions/code-style@v4
  #       with:
  #         python-version: ${{ env.MAIN_PYTHON_VERSION }}

  # docs-style:
  #   name: Documentation Style Check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: PyAnsys documentation style checks
  #       uses: ansys/actions/doc-style@v4
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}

  create-docstrings:
    name: Create docstrings
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ansys/mechanical:23.2.0
      options: --entrypoint /bin/bash
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt update
          apt install -y lsb-release
          apt install -y python3-pip
          apt install -y python3.8-venv
          apt install -y mono-complete
          pip3 install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org pip setuptools
          pip3 install --upgrade pip flit
          pip3 install ansys-pythonnet
          pip3 install sphinx

      - name: Run main.py
        env:
          LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
          ANSYSCL232_DIR: /install/ansys_inc/v232/licensingclient
          ANSYSLMD_LICENSE_FILE: 1055@${{ secrets.LICENSE_SERVER }}
          ANSYS_WORKBENCH_LOGGING_CONSOLE: 0
          ANSYS_WORKBENCH_LOGGING: 0
          ANSYS_WORKBENCH_LOGGING_FILTER_LEVEL: 2
          AWP_ROOT232: /install/ansys_inc/v232
          NUM_CORES: 1
        run: |
            python3 main.py
        continue-on-error: True

      - name: Install package
        run: |
          cd package && pip install -e .
      
      - name: Run Ansys documentation building action
        uses: ansys/actions/doc-build@v4
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          dependencies: "pandoc"
  
