name: Process Markdown Files from Sphinx

on:
  workflow_dispatch:
    inputs:
      html_folder_path:
        description: 'Folder containing html files to process for toc creation'
        required: true
      folder_path:
        description: 'Folder containing markdown files to process'
        required: true
      output_path:
        description: 'Folder to save processed markdown files'
        required: true

jobs:
    process_markdown_files:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: '3.10'

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pyyaml

        - name: Create Output Directory
          run: |
            # mkdir -p ${{ github.event.inputs.output_path }}
            mkdir -p output

        - name: Clean ID in first row
          run: |
            python scripts/01-clean-id.py --input_folder ${{ github.event.inputs.folder_path }}
            # python scripts/01-clean-id.py --input_folder markdown/input/rigid

        - name: Clean Empty Rows
          run: |
            python scripts/02-clean-empty-row.py --input_folder ${{ github.event.inputs.output_path }}
            # python scripts/02-clean-empty-row.py --input_folder output

        # - name: Create Table of Contents
        #   run: |
        #     python scripts/03-create-toc-from-html-mechanical.py --input_folder ${{ github.event.inputs.html_folder_path }}
        #     # python scripts/03-create-toc-from-html-mechanical.py --input_folder output

        - name: Add header to tables
          run: |
            python scripts/04-add-header-to-tables.py --input_folder ${{ github.event.inputs.output_path }}
            # python scripts/04-add-header-to-tables.py --input_file output/toc.yml

        - name: Remove links in heading
          run: |
            python scripts/05-remove-link-in-heading.py --input_folder ${{ github.event.inputs.output_path }}
            # python scripts/05-remove-link-in-heading.py --input_file output/toc.yml

        - name: Upload to GitHub Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: processed-markdown-files
            path: output/
